version: 2.1

orbs:
 codecov/codecov@3.2.4
  

jobs:
  build:
    docker:
      - image: circleci/android:latest
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: gradlew assembleDebug # Build debug variant
      - run: gradlew assembleRelease # Build release variant
      - android/save-gradle-cache

  test:
    docker:
      - image: circleci/android:latest
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: gradlew testDebug # Run instrumentation tests
      - run: gradlew connectedTestDebug # Run UI tests
      - android/save-gradle-cache

  deploy:
    docker:
      - image: circleci/android:latest
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: gradlew assembleRelease # Build release variant
      - android/save-gradle-cache

workflows:
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy
    requires:
      - build
      - test

